badlogic/heissepreise

README.md
analysis.js
site/utils.js

Analog zu den Billigmarkenfiltern hier ein Filter für Bio-Produkte.
Ich bin mir nicht sicher ob/wie das mit einer bestehenden Datenbank mergt, aber es funktioniert jedenfalls from scratch

Filter für Bio-Produkte

---

analysis.js
site/cart.html
site/cart.js
site/utils.js

The data fetching is a bit hacky due to the limits of the dm API, but it works very well now.
To my surprise, a lot of brands are significantly cheaper at dm than Spar and Billa

Add support for dm

---

README.md
analysis.js
site/cart.html
site/cart.js
site/utils.js

* Not all products have prices (will be skipped)
* Not all products have units (render empty string)

Add limited support for LIDL

---

analysis.js

Status quo: Store data is fetched one store after another.
This PR improve resilience of data fetching and makes fixing #15 obsolete

Fetch store data in parallel

---

index.js

Create `data` directory if not present. Additionally small refactoring, added a constant for the folder name.
Previous discussion: https://github.com/badlogic/heissepreise/pull/19

Bugfix missing data dir

---

README.md
analysis.js
site/cart.html
site/cart.js
site/utils.js

Add MPREIS support

---

analysis.js
stores/billa.js
stores/dm.js
stores/hofer.js
stores/index.js
stores/lidl.js
stores/mpreis.js
stores/spar.js

Allow to add new stores without copy pasting the same thing overall

Refactor to generic store syntax

---

site/utils.js

the initial lastPrice is a float, needs to be an object

Fix lastPrice to object

---

site/aktionen.js
site/cart.js
site/carts.js
site/changes.js
site/main.js
site/style.css
site/utils.js

Allow the collapsing of tables into datalists

Add responsive tables

---

stores/unimarkt.js

this should detect about 99% of bio prodcuts. in some rare cases there is no "bio" in the products name like "alnatura mango lassi"

Detect Unimarkt Bio Products

---

README.md
analysis.js
index.js
site/billiger.js
site/changes.js
stuff.js

The numbering of points on the `README.md` was kinda wrong and some added some linting to the file. 
Additionally removed some unused variables or marked them with underscore in various `.js` files.

lint: 📝 update readme and removed some unused variables

---

.editorconfig
site/cart.js
site/carts.js
site/utils.js

- converted `carts` logic into a class `ShoppingCart`
- simplified `currentDate()` & `getQueryParameter()` functions (note: `new URL` browser support, see <https://caniuse.com/?search=URL>)

refactor: :recycle: refactor some utils

---

analysis.js
site/main.js
site/utils.js

- Utilizes searchParam c for chart item selection
- Display Query Search on every search
- Use store:id as unique identifier
Additionally fixes conversions for old data (uri param from clown compression)

Share search

---

.gitignore
analysis.js
index.js
site/utils.js

Fetch canonical compressed in parallel

---

stores/hofer.js
stores/mpreis.js
stores/spar.js
stores/utils.js

Depends on #49 for a utility function, so merge that one first.
Fixes issues mentioned here:
https://github.com/badlogic/heissepreise/pull/10#issuecomment-1566297593
https://github.com/badlogic/heissepreise/pull/10#issuecomment-1566297892

Fix mpreis units

---

site/aktionen.html
site/billiger.html
site/carts.html
site/changes.html
site/index-new.html
site/index.html

Add 🔥 as favicon

---

site/cart.js
site/carts.js

Apply encodeURIComponent on cart name for link generation

Escape cart name, fixes badlogic/heissepreise#47

---

site/utils.js

To make it easier to select/deselect all stores.

add 'alle' checkbox

---

site/cart.js
site/style.css
site/utils.js

- Allows Search Input & Filters to be displayed while scrolling
- Filter Toggle (only sticky) to hide filters
- distinct budgetBrands (title attribute to show details)

PoC: Sticky Header

---

package.json

Add missing husky install script

---

analysis.js

skip already gzipped files in json -> gzip migration

---

stores/billa.js
stores/dm-de.js
stores/dm.js
stores/hofer.js
stores/lidl.js
stores/mpreis.js
stores/penny.js
stores/rewe-de.js
stores/spar.js
stores/unimarkt.js
stores/utils.js

- rename `conversions` to `units`
- gather common units in `utils.globalUnits`
- run prettier on stores folder

Units handling for Unimarkt, some cleanup

---

stores/dm-de.js
stores/dm.js

Fixes #45 (and makes the warning messages easier to understand)

Fixed DM-DE queries

---

analysis.js
stores/hofer.js
stores/spar.js
stores/utils.js

fallback argument in convertUnit

---

site/_templates/_footer.html
site/style.css

Weil du das ja jetzt hostest @badlogic. Weiß nicht wie viel sowas wirklich bringt, seh diese Disclaimers halt überall, vielleicht bringts ja was wenn irgendwo folgenschwer zwei Zahlen vertauscht werden 🙃
Überlass dir ob du das drin haben magst

Add legal disclaimer

---

stores/unimarkt.js

Products like pet food, soap, shampoo, etc.

Add missing unimarkt "haushalt" category

---

stores/unimarkt.js

Use 1 stk as fallback (7 articles so far).
The other 20 are using "mbe" -> wg (Waschgang).
Changes:
```json
[
{
"quantity": " -> 1",
"unit": " -> stk",
"name": "Aeroxon Ameisen-Köderdose 1 Stk Insekten- und Schädlingsbekämpfung",
"store": "unimarkt"
},
{
"quantity": " -> 1",
"unit": " -> stk",
"name": "Aeroxon Lebensmittelmotten-Falle 2 Stk Insekten- und Schädlingsbekämpfung",
"store": "unimarkt"
},
{
"quantity": " -> 1",
"unit": " -> stk",
"name": "Alnatura Bio Dinkel Backerbsen",
"store": "unimarkt"
},
{
"unit": "mbe -> wg",
"name": "Ariel Flüssig 30WG, Color",
"store": "unimarkt"
},
{
"unit": "mbe -> wg",
"name": "Ariel Flüssig 30WG, Frühlingsfrische",
"store": "unimarkt"
},
{
"unit": "mbe -> wg",
"name": "Ariel Vollwaschmittel flüssig",
"store": "unimarkt"
},
{
"unit": "mbe -> wg", …
```

Fix unimarkt units

---

site/cart.html
site/changes.html
site/utils.js

… this ignores the fact that you can use  `! ` filters (but it's not documented anyway so users won't know it exists)
Also I wanted to use a global const rather than hardcoding the 3 value, but this would require including the other file…? Maybe you want some global `constants.js` include at some point.

add min characters needed for search to placeholder

---

README.md
package-lock.json
package.json
postcss.config.js
site/_templates/_header.html
site/cart.js
site/changes.js
site/imprint.html
site/index.js
site/style.css
site/tailwind.css
site/utils.js
tailwind.config.js

We use PostCSS für building tailwind with the required classes, to build the css with only the required class run `npm run build`, make sure to npm install before.

Tailwind Build process

---

site/views/items-filter.js

reflect checked state of "Alle" stores for the user

Fix select all stores ux

---

site/_templates/_footer.html
site/js/misc.js
site/style.css
site/views/items-list.js

- added global hover effect on links (underline)
- changed footer links style to stand out more and allow hover effect to take place
- added utility function to format numbers into locale string `at-DE`
- table count uses the locale string format of the number, this helps to better see the thousands of results ;-)

feat: 🎨 style changes

---

site/_templates/_footer.html
site/_templates/_header.html

- added missing aria tags for non conform links
- set correct homepage language to allow better detection for auto translation and text to speech
- (SEO) add missing description meta tag

feat: 🎨 improve accessability

---

stores/unimarkt-categories.json
stores/unimarkt.js

Works localy at my machine... I hope so at your's ;-D

Unimarkt Categories

---

stores/dm.js

Should take care of this issue with DM request paging: https://github.com/badlogic/heissepreise/issues/124
As I was touching this file, my IDE hinted to this bitwise OR issues, which I also fixed.

DM adjust queries

---

site/data/preisgesenkt-cart.json

Fix typo in preisgesenkt-cart.json
